# task_descriptions.py
# Plain-English descriptions for every task in rebuild_tracker.py
# Key = exact text content of the task (without the [CATEGORY] prefix)
# If a task is not found here, it renders without a description (graceful fallback)

DESCRIPTIONS = {
  # ─── PHASE 0 ───
  "shadcn/ui installed and initialized": "The shadcn/ui component library is added to the project — it provides accessible, customizable UI primitives like buttons, dialogs, and inputs.",
  "Inter font installed in root layout": "Google's Inter typeface is loaded globally, giving the entire app a modern, clean, and highly-legible text style.",
  "Core dark-mode tokens exist in globals.css": "CSS variables for the dark-mode color palette (backgrounds, borders, text, accents) are defined once in globals.css so every component can reference them.",
  "Typography scale is fully defined": "Font sizes, weights, and line heights form a consistent scale — headings, body text, and captions all feel visually harmonious.",
  "Semantic token set is complete": "Every color token has a meaningful name (e.g. --color-surface, --color-text-muted) so teams talk about intent, not raw HEX codes.",
  "App no longer uses hardcoded colors or inline style-heavy UI": "No component directly writes #1a1a2e or style={{ color: 'red' }} — all colors go through the token system, making theme changes instant.",
  "Design Tokens Documentation Page (internal token reference)": "A living reference page inside the app lists every token name, CSS variable, and its visual output — prevents developers from re-inventing decisions.",
  "Loading skeletons on all list pages (contacts, campaigns, templates)": "While data is being fetched, a pulsing placeholder layout appears instead of a blank screen — improves perceived performance significantly.",
  "Dark / Light mode toggle (CSS variable swap)": "A toggle switches the entire app between dark and light themes by swapping the root CSS variable values — no components need to change.",
  "Button.tsx": "A shared Button component with consistent sizing, colors, loading state, and disabled state — used everywhere so buttons always look the same.",
  "Badge.tsx": "A small inline label component for status indicators like 'Active', 'Paused', 'Draft' — color-coded and reusable.",
  "HealthDot.tsx": "A tiny colored dot that signals system health at a glance — green for healthy, yellow for degraded, red for down.",
  "LoadingSpinner.tsx": "An animated spinner shown during async operations — ensures users always have feedback that work is in progress.",
  "StatCard.tsx": "A card component that displays a single metric (e.g. 'Total Sent: 12,450') with an icon, a number, and a trend indicator.",
  "StatusBadge.tsx": "A badge specifically designed for status values — maps status strings to distinct color themes automatically.",
  "ConfirmModal.tsx": "A confirmation dialog that asks the user to explicitly approve dangerous actions like 'Delete 1,000 contacts' before proceeding.",
  "Toast.tsx": "A small pop-up notification (top-right corner) for showing success, error, or info messages after async operations complete.",
  "PageHeader.tsx": "A consistent header block shown at the top of every page — includes the page title, breadcrumb, and an optional action button.",
  "DataTable.tsx": "A reusable sortable, paginated table component with column definitions — contacts list, campaigns list, and templates all use this.",
  "EmptyState.tsx": "A friendly illustration + message shown when a list has zero items — replaces blank white space with a clear call-to-action.",
  "Breadcrumb.tsx": "A trail of links (e.g. Campaigns › Test Campaign › Analytics) that shows the user where they are inside the app hierarchy.",
  "src/components/ui/index.ts": "A barrel export file — lets you write `import { Button, Badge } from '@/components/ui'` instead of separate import lines per component.",
  "Tailwind config maps tokens to utility names": "The tailwind.config.ts file bridges CSS variables to Tailwind class names so you can write `text-accent` and it resolves to the correct CSS variable.",
  "All mapped Tailwind token names resolve to actual CSS variables": "A verification check: every Tailwind utility added in the config actually has a corresponding CSS variable in globals.css — no dangling references.",
  "Every destructive action uses ConfirmModal": "Any button that deletes or permanently modifies data is blocked behind a ConfirmModal — prevents accidental data loss.",
  "Every async form submit uses loading state consistently": "When a form is submitted, its button shows a spinner and disables itself — prevents double-submissions and communicates that work is happening.",
  "Every API success path uses toast feedback consistently": "After a successful API call, a green toast appears — users always know their action was saved.",
  "Every API error path uses toast feedback consistently": "When an API call fails, a red toast appears with a short message — users never see a blank failure silently.",
  "Every empty list uses EmptyState": "All list pages (contacts, campaigns, templates) show the EmptyState component instead of a blank div when there is no data.",
  "Every list page has consistent search and filter behavior": "Search boxes, filter dropdowns, and pagination behave identically across all list pages — users only learn the pattern once.",
  "Mobile navigation is complete end-to-end": "The sidebar collapses into a hamburger menu on small screens, all pages are scrollable, and no UI is clipped or hidden on mobile.",
  "Remove global *:focus { outline: none }": "Removing this rule restores visible keyboard focus indicators — a critical accessibility requirement for users navigating by keyboard.",
  "Modal accessibility is complete (focus trap + restore)": "When a modal opens, keyboard focus is trapped inside it; when it closes, focus returns to the triggering element — standard a11y behavior.",
  "Icon-only buttons are fully labeled app-wide": "Every button that shows only an icon has an aria-label attribute so screen readers can announce its purpose.",
  "44x44 touch-target guidance is satisfied app-wide": "All interactive elements are at least 44×44 CSS pixels in size — Apple/Google accessibility guideline to prevent mis-taps on mobile.",
  "Mailhog added to docker-compose.yml": "Mailhog is a local email catcher — emails sent during local development go to a web UI instead of real inboxes, which is safe and observable.",
  "scripts/seed_dev_data.py added": "A script that populates the local database with realistic sample data (tenants, contacts, campaigns) so developers can test the UI without real data.",
  ".env.example fully documents all required variables": "A complete template of all environment variables with comments explaining where to get each value — so new developers can set up the project without asking anyone.",

  # ─── PHASE 1 ───
  "Custom email/password auth (bcrypt + custom JWT)": "Passwords are hashed with bcrypt before storage. After login, a signed JWT token is issued — the token is required for every protected API call.",
  "Tenant membership model (users, tenants, tenant_users)": "Three linked tables: users (who you are), tenants (your workspace), and tenant_users (your role in that workspace). One user can have multiple workspaces.",
  "Onboarding flow (4-step wizard + progressive endpoints)": "New tenants go through a wizard (workspace name → use-case → integrations → scale) before seeing the full dashboard — ensures every account is properly configured.",
  "JWT middleware (tenant_id, role, email, user_id verification)": "Every API request passes through middleware that verifies the JWT, extracts tenant_id/role/user_id, and injects them into the request context for all route handlers.",
  "Active-tenant guard exists": "A middleware check blocks API calls from tenants whose account is suspended or still in the onboarding state.",
  "Workspace switching exists": "A user who belongs to multiple workspaces can switch between them — the JWT is re-issued for the selected workspace.",
  "/auth/me fully implemented": "The GET /auth/me endpoint returns the full profile of the currently logged-in user — name, email, role, plan, and workspace details.",
  "All onboarding endpoints use JWT-only tenant resolution consistently": "No onboarding route reads tenant_id from the request body or query string — it always comes from the verified JWT, preventing spoofing.",
  "Login page": "The frontend login screen with email/password fields, error messaging, and a link to sign up or reset password.",
  "Signup page": "The registration screen where new users create their account — collects name, email, and password, then triggers email verification.",
  "reCAPTCHA on Signup form": "Google reCAPTCHA is added to the signup form to block automated bot registrations.",
  "Onboarding wizard (workspace > use-case > integrations > scale > complete)": "The multi-step setup flow shown to new tenants — it collects workspace name, intended email use case, connected integrations, and expected volume.",
  "Interactive onboarding checklist on dashboard": "The dashboard shows a setup checklist (verify email, add a sender domain, create first campaign) that disappears once all steps are complete.",
  "Sidebar navigation layout": "The left-side navigation bar with links to Contacts, Campaigns, Templates, Analytics, Settings — collapses on mobile.",
  "Auth context exists": "A React context that stores the current user's session (token, role, tenant_id) and provides it to any component via a hook.",
  "Middleware redirects exist": "Next.js route middleware that checks the JWT/session cookie and redirects unauthenticated users to the login page automatically.",
  "Route protection is fully centralized and consistent": "Every protected page uses the same single middleware check — no page accidentally forgets to protect itself.",
  "JWT carries tenant identity": "The JWT payload includes tenant_id so every API call automatically carries workspace context without an extra database lookup.",
  "X-Tenant-ID is validated against JWT when used": "If a request sends an X-Tenant-ID header, the server verifies it matches the tenant_id inside the JWT — prevents tenants from accessing other users' data.",
  "Onboarding tenants are blocked from active-tenant routes": "A guard prevents a tenant still in the onboarding wizard from calling production API endpoints like 'send campaign'.",
  "Social Auth (Google, GitHub) via OAuth 2.0 / Supabase": "Users can sign in with their Google or GitHub account instead of creating a password — handled via Supabase's OAuth integration.",
  "Rate limiting on login + registration endpoints (per IP, per email)": "Login and signup are limited to 10 attempts per minute per IP/email — prevents brute-force password attacks.",
  "Email verification required before onboarding completes": "A user must click the verification link in their email before the onboarding wizard can advance past step 1.",
  "Short-lived access tokens (15-30 min) + silent refresh tokens": "Access tokens expire quickly so stolen tokens have a short window. Refresh tokens automatically issue new access tokens in the background.",
  "Token revocation via token_version counter (force-logout all devices)": "A counter on each user row is incremented to invalidate all existing JWTs instantly — useful for 'sign out everywhere' or account compromise scenarios.",

  # ─── PHASE 1.5 ───
  "Remove custom /auth/forgot-password endpoint": "The hand-rolled forgot-password route was replaced by Supabase Auth's built-in email flow, which handles token generation and expiry securely.",
  "Remove custom /auth/reset-password endpoint": "Same as above — the custom password-reset handler was removed in favor of Supabase Auth's standard reset flow.",
  "reCAPTCHA token verification endpoint/middleware": "Backend middleware that validates the reCAPTCHA token sent from the signup form — prevents bots from auto-creating accounts.",
  "Audit logs table (who did what, when, on which record — metadata only)": "A database table that records every important action (who deleted contacts, who sent a campaign) — stores metadata only, never actual email content.",
  "Audit log table is write-only / immutable (no UPDATE or DELETE allowed)": "Once a log row is written, it can never be changed or deleted — even by admins — making it a tamper-proof activity record.",
  "Log severity levels: INFO / WARNING / CRITICAL on every log row": "Each audit log entry has a severity tag: INFO for normal events, WARNING for unusual ones, CRITICAL for high-risk actions like bulk deletes.",
  "Auto-alert on CRITICAL log events (bulk delete >1000, suspicious login)": "When a CRITICAL event occurs, the system automatically emails the workspace owner — e.g. 'Someone deleted 2,000 contacts from your account'.",
  "Configure Supabase Auth SMTP to use shrmail.app@gmail.com": "Supabase's auth emails (verification, password reset) are routed through your own Gmail account instead of Supabase's generic sender.",
  "Fix forgot-password page — Supabase Auth built-in reset email flow": "The frontend forgot-password page now calls Supabase Auth's built-in reset endpoint instead of a custom one.",
  "Fix reset-password page — Supabase Auth password update": "The reset-password page uses Supabase Auth's updateUser() call to change the password after the reset link is clicked.",
  "Test: sign up > verify email > login > forgot password > reset": "An end-to-end manual test confirming the full auth lifecycle works: create account, verify email, log in, reset password.",
  "Audit log viewer with severity filter (INFO / WARNING / CRITICAL)": "A page in the admin settings that shows the audit log timeline with filter buttons for severity level.",
  "MFA via TOTP for workspace admins": "Workspace admins can enable time-based one-time passwords (Google Authenticator style) as a second login factor.",
  "[AUDIT FIX 1] Cross-tenant webhook suppression — add tenant_id filter to _suppress_contact() in webhooks.py (0.5d)": "Critical bug: when AWS SES reports a bounce, the code suppresses that email address across ALL tenants on the platform. Fix: add a tenant_id filter so only the correct workspace's contact is suppressed.",
  "[AUDIT FIX 2] JWT refresh token model — 30-min access token + HttpOnly refresh cookie + token_version revocation on users table (2d)": "Security fix: current JWTs are valid for 7 days and cannot be revoked. Fix: shorten to 30 minutes, add a long-lived refresh token in an HttpOnly cookie, and allow instant revocation via a token_version column.",
  "[AUDIT FIX 3] Lock CORS to FRONTEND_URL env var — no wildcard in production (0.5d)": "Security fix: the API currently allows requests from any website (CORS wildcard). Fix: restrict it to only your frontend domain by reading FRONTEND_URL from the environment.",
  "[AUDIT FIX 4] Enable SSL cert verification in worker — remove ssl.CERT_NONE; add AMQP_SKIP_TLS_VERIFY dev flag (0.5d)": "Security fix: the email worker disables SSL certificate checking, which allows man-in-the-middle attacks. Fix: enable cert verification and add a dev-only env flag to skip it locally.",
  "[AUDIT FIX 5] Delete /contacts/upload + /test-send from main.py; remove db_check.py, db_check2.py, generate_test_csv.py from repo root (0.5d)": "Cleanup: two scaffolding endpoints bypass security checks and should be removed from the production API. Also remove dev scripts committed to the repo root.",
  "[AUDIT FIX 6] Remove duplicate events router registration — second app.include_router(events_router.router) in main.py (0.5d)": "Bug fix: the events router is registered twice in main.py. While harmless at runtime, it doubles the routes in the API docs and is a maintenance hazard.",
  "[FRIEND AUDIT FIX 17] OAuth State Parameter — Require and validate a random state string in the Google/GitHub OAuth flow to prevent CSRF (0.5d)": "Security fix: the Google/GitHub login flow is missing a state parameter. Without it, an attacker can trick users into logging in under the attacker's account (OAuth CSRF). Fix: generate and validate a random state string on each login attempt.",

  # ─── PHASE 1.6 ───
  "Data export API (async job — POST > job_id > poll > download ZIP)": "Tenants can request a full data export. It runs as a background job and returns a download link once ready — avoids timeouts on large datasets.",
  "Right to be forgotten: DELETE /contacts/{id}/anonymize (anonymize PII, keep row)": "GDPR requirement: anonymize a contact's personal data (name, email) but keep the row for statistical integrity — the data is pseudonymized, not deleted.",
  "Soft delete pattern: deleted_at on contacts, campaigns, templates (30-day restore)": "Instead of permanently removing records, mark them with a deleted_at timestamp. They disappear from the UI but can be restored within 30 days.",
  "Consent tracking: consent_source, consent_date, consent_ip on contacts": "Each contact records how and when they gave consent to receive emails — essential for GDPR audits and CAN-SPAM compliance.",
  "Data retention policy: auto-flag contacts inactive >24 months for purge": "Contacts who haven't engaged in over 2 years are automatically flagged for review — keeping the list clean and compliant with data minimization rules.",
  "Consent re-validation: exclude contacts with consent >24 months old": "Campaigns automatically skip contacts whose consent is older than 24 months — prevents emailing people who haven't opted in recently.",
  "Do Not Contact (DNC) global suppression list (platform-level, blocks all emails)": "A platform-level list (not per-tenant) of email addresses that can never receive emails from any tenant — e.g. addresses that have reported legal complaints.",
  "Restore modal for soft-deleted items": "A UI element that lets users un-delete a contact, campaign, or template within the 30-day recovery window.",
  "Data export button in Settings": "A button on the Settings page that triggers the async data export job for the current tenant.",
  "Consent column visible in contacts table": "The contacts list shows each contact's consent source and date so operators can audit consent at a glance.",
  "Privacy policy / Terms page linked from footer": "The application footer contains links to the Privacy Policy and Terms of Service — required for legal compliance and user trust.",

  # ─── PHASE 2 ───
  "CSV/XLSX ingestion": "Tenants can upload a CSV or Excel file of contacts. The file is parsed and each row is inserted into the contacts table for the current tenant.",
  "Real-time contact ingestion API (POST /v1/contacts for forms/CRM webhooks)": "An API endpoint that accepts individual contact records in real time — used by web forms, CRMs, or any external system to add contacts programmatically.",
  "Email validation: syntax check + MX record check + disposable email detection": "Each email is validated at three levels: correct format, the domain actually has a mail server, and the domain isn't a known disposable-email provider.",
  "Contact scoring system (engaged / at-risk / inactive / risky)": "Each contact is automatically scored based on their engagement history — high openers are 'engaged', long-inactive contacts are 'at-risk', etc.",
  "Upload preview endpoint": "Before committing a CSV import, an endpoint parses the file and returns a preview of the first few rows and the detected columns for the user to review.",
  "Async import job creation": "After the user confirms the column mapping, an import job record is created in the database and handed off to the background worker — the API returns immediately.",
  "RabbitMQ background import worker": "A background process consumes import jobs from the queue and processes each CSV row — deduplicates contacts and inserts them in batches.",
  "Import batch history": "Every CSV upload creates a 'batch' record with stats (total rows, imported, duplicates, errors) so tenants can review past imports.",
  "Deduplication (in-memory + Supabase upsert on tenant_id, email)": "Contacts are deduplicated both in memory (within the file) and at the database level using an upsert — the same email address is never inserted twice per tenant.",
  "Contact status (subscribed, unsubscribed, bounced, complained)": "Each contact has an explicit status that controls whether emails are sent to them. Bounced and complained contacts are automatically excluded from campaigns.",
  "Domain summary endpoint and email_domain storage": "Each contact's email domain is extracted and stored separately. An endpoint returns a summary of contacts grouped by domain (e.g. 450 @gmail.com, 200 @yahoo.com).",
  "Batch-scoped domain filtering": "When selecting a campaign audience, tenants can filter contacts to a specific domain within a specific import batch.",
  "Segmentation filters (filter by field/operator/value)": "Contacts can be filtered by any field (e.g. status = subscribed, country = India) to build targeted audience segments for campaigns.",
  "Bulk delete": "Tenants can select and delete multiple contacts at once — either selected rows or an entire batch.",
  "Contact search endpoint (email, name, tag)": "A search endpoint that queries contacts by email address, name, or tag — used by the search box on the contacts list page.",
  "Contact update endpoint (email + custom fields)": "An endpoint that updates a contact's email address or custom field values.",
  "Tags CRUD API (add/remove/list tags per contact)": "Contacts can be tagged with labels (e.g. 'VIP', 'newsletter'). This API manages creating, assigning, removing, and listing tags.",
  "Soft delete: deleted_at column on contacts (restore within 30 days)": "When a contact is deleted, it's marked with a timestamp rather than removed — it can be restored within 30 days.",
  "Suppression list API (GET /contacts/suppression)": "An endpoint that returns all suppressed contacts (bounced, unsubscribed, complained) for the current tenant — used on the Suppression List page.",
  "Export contacts API": "An API that generates a CSV download of all contacts for the current tenant — useful for backups or migrations.",
  "FIX: GET /suppression route collision with /{contact_id} resolved": "Bug fix: the /contacts/suppression endpoint was being matched by the /{contact_id} wildcard route, returning a 'contact not found' error. Resolved by reordering route registration.",
  "FIX: Suppression list jwt_payload arg bug fixed (was returning 0 results)": "Bug fix: the suppression list endpoint was not extracting tenant_id from the JWT correctly, causing it to return zero results for all tenants.",
  "Contacts list page (table with search and pagination)": "The main contacts screen — a paginated table with a search bar, status filters, and bulk action buttons.",
  "Import contacts modal with preview and mapping": "A dialog that guides the user through uploading a CSV, previewing its contents, and mapping columns to contact fields before confirming the import.",
  "Async import progress polling": "After an import starts, the frontend polls an endpoint every 3 seconds to show live progress (rows processed, errors) to the user.",
  "Import history tab": "A tab on the Contacts page listing all past import batches — shows date, file name, row count, and import status.",
  "Batch detail page": "A detail page for a specific import batch — shows a breakdown of imported contacts, duplicate counts, and any row-level errors.",
  "Batch detail domain filtering": "On the batch detail page, contacts are grouped and filterable by email domain.",
  "Contact status badges (subscribed / unsubscribed / bounced)": "Colored badges in the contacts table that show the status of each contact at a glance.",
  "Segment builder UI (filter by field, value)": "A UI that lets tenants build audience segments by adding filter rules (field + operator + value) before launching a campaign.",
  "Bulk action buttons (delete selected)": "Checkboxes on the contacts table rows, plus a 'Delete Selected' button in the toolbar, for mass management.",
  "Contact detail editing (email + custom fields)": "Clicking on a contact opens an edit panel where the tenant can update the email address or any custom field.",
  "Contact detail page (individual contact activity)": "A dedicated page for a single contact showing their full activity history — emails received, opens, bounces, and unsubscribes.",
  "Export contacts to CSV button": "A button on the contacts page that triggers a CSV download of the current filtered contact list.",
  "Tags UI (add/remove tags on contacts)": "An inline UI on the contact detail view to add or remove tags from a contact.",
  "Suppression list page (view bounced/spam/unsubscribed contacts)": "A dedicated page that shows all suppressed contacts — helps tenants audit who won't receive emails and why.",
  "Campaign audience selection supports batch-domain targeting": "When creating a campaign, tenants can choose to send to all contacts from a specific imported batch or domain.",
  "Campaign audience selection supports multi-domain selection inside a batch": "Tenants can select multiple domains within a single batch as the campaign audience.",
  "Duplicate resolution UI (show conflict, let tenant choose which values to keep)": "When an imported contact already exists, a UI presents both the old and new values side-by-side and asks the tenant which to keep.",
  "Contact scoring badge visible in contacts list": "The contacts table shows a small scoring badge (Engaged / At-Risk / Inactive / Risky) for each contact.",
  "[FRIEND AUDIT FIX 18] Streaming CSV Uploads — Replace pandas in-memory parser with async chunked byte stream parsing to prevent OOM API crashes (2d)": "Performance fix: the current CSV import reads the entire file into RAM using pandas. For large files (100k+ rows), this crashes the API. Fix: parse the CSV as a streaming byte sequence so memory usage stays constant regardless of file size.",

  # ─── PHASE 3 ───
  "Template CRUD": "Create, read, update, and delete email templates — the core data management API for the template engine.",
  "Category": "Templates can be organized by category (e.g. Newsletter, Promotional, Transactional) to make finding the right base design easier.",
  "Persist compiled HTML from the active block editor": "When a tenant saves a block-editor template, the compiled HTML is stored alongside the design JSON so it can be previewed and sent without re-compiling.",
  "Preset gallery and preset-driven template creation": "A gallery of pre-built starter templates (welcome email, newsletter, promo) that tenants can select as a starting point instead of building from scratch.",
  "Template versioning (save history)": "Every time a template is saved, the previous version is kept — tenants can view a timeline of changes and roll back to any earlier version.",
  "Plain text auto-generator (sync from HTML for spam filters)": "Automatically generates a plain-text version of the email from the HTML body — important for spam filter scores and email clients that don't render HTML.",
  "Public View Online link (render template in browser without login)": "A public URL is generated for each campaign that renders the email in the browser — shown as a 'View this email online' fallback link.",
  "Templates list page (grid of template cards with thumbnails)": "The main templates screen showing cards for each template with a visual thumbnail preview.",
  "Create template (blank canvas and preset entry flow)": "The UI flow for creating a new template — choose between a blank canvas or starting from a preset gallery card.",
  "Structured block editor (rows > columns > blocks)": "The drag-and-drop email editor where tenants compose emails by combining row containers, column layouts, and content blocks (text, image, button).",
  "Server-side compile preview (design_json > MJML > HTML)": "The template JSON is sent to the server and compiled through MJML into responsive HTML — the result is shown as a live preview in the editor.",
  "Plain Text (Auto-generated) | Plain Text (Custom) tabs": "Two tabs in the template editor: one showing the auto-generated plain text, and one where the tenant can write a custom plain-text version.",
  "Send test email button (enter email address > receive real email)": "A button in the template editor that sends the current template to any entered email address so the tenant can preview it in a real inbox.",
  "Duplicate template button": "A button that clones an existing template into a new draft — useful for creating variations of a proven design.",
  "Category filter tabs on template list": "Tabs across the top of the templates list that filter templates by their category.",
  "Version history panel (see and restore older versions)": "A sidebar panel in the template editor that shows past saves and allows rolling back to any previous version with one click.",
  "Dynamic placeholder guide (show list of {{merge_tags}} user can use)": "A helper panel in the editor listing all available merge tags like {{first_name}}, {{company}}, and {{unsubscribe_link}} with copy-to-clipboard buttons.",
  "Spam score checker (SpamAssassin-style heuristics before campaign send)": "Analyzes the email content for common spam triggers (ALL CAPS, excessive punctuation, spammy phrases) and shows a score before the campaign is sent.",
  "Mobile preview mode (375px viewport toggle in template editor)": "A toggle in the template editor that renders the preview at mobile screen width (375px) to check how the email looks on phones.",
  "Inbox preview simulation (Gmail, Outlook, Apple Mail rendering)": "Shows how the email will render in the most popular email clients — Gmail, Outlook, and Apple Mail all have different rendering engines.",

  # ─── PHASE 4 ───
  "Campaign CRUD": "Create, read, update, and delete campaigns — the core data management API for the campaign engine.",
  "Snapshot campaign content + dispatch intents at send time": "At the moment a campaign is sent, the system takes a snapshot of the template HTML and creates one dispatch record per recipient — so later content changes don't affect an in-progress send.",
  "Spintax + merge tags": "Spintax ({Hello|Hi|Hey}) and merge tags ({{first_name}}) are applied per-recipient — each email looks slightly different and is personalized.",
  "Scheduled sending": "Campaigns can be scheduled for a future date/time. The scheduler checks for due campaigns every 60 seconds and dispatches them automatically.",
  "Pause/resume campaign": "A running campaign can be paused mid-send to halt delivery temporarily, then resumed — useful for catching mistakes after launch.",
  "Cancel campaign mid-send": "A campaign can be permanently cancelled while in progress — all remaining unsent dispatch intents are marked cancelled.",
  "Resend to unopened contacts": "After a campaign completes, the tenant can trigger a resend (optionally with a different subject) to contacts who never opened the original email.",
  "FIX: exclude_suppressed=True enforced in scheduler.py, main.py, campaigns.py": "Bug fix: several code paths were not consistently excluding suppressed (bounced/unsubscribed) contacts when building the dispatch list. This is now enforced everywhere.",
  "Campaigns list page (status badges, stats)": "The main campaigns screen — a list of all campaigns with status badges (draft, scheduled, sending, sent), and quick stats (sent count, open rate).",
  "Create campaign wizard (details > audience > content > review)": "A multi-step wizard for creating a campaign: fill in basic details, choose the audience, pick a template, then review before sending.",
  "Campaign detail page": "A page showing everything about a single campaign: its settings, current status, dispatch progress, and a link to analytics.",
  "Pre-send checklist UI": "Before a campaign is sent, a checklist verifies critical elements are in order: subject line entered, unsubscribe link present, audience not empty, sender domain verified.",
  "Schedule picker (date/time input for scheduled send)": "A date/time picker UI for setting when a scheduled campaign should be dispatched.",
  "Pause button / Cancel button on in-progress campaign": "Action buttons on the campaign detail page to pause or cancel a campaign that is currently sending.",
  "Send test email modal (enter email address, preview)": "A modal inside the campaign wizard where the tenant can send themselves a test version of the campaign before the real send.",
  "Automated pre-send validation (no subject / no unsub / blank body blocks send)": "The backend automatically rejects campaign sends that are missing a subject line, unsubscribe link, or email body — catches common mistakes before they reach recipients.",
  "Send throttling control (configurable per-minute rate, ETA shown in UI)": "Tenants can configure how many emails per minute are sent (e.g. 500/min for warm-up) and the UI shows an estimated completion time.",
  "Send to 5% sample first mode (review analytics before full broadcast)": "An option to send the campaign to a 5% random sample of the audience first, review open/bounce rates, and then decide whether to send to the remaining 95%.",

  # ─── PHASE 5 ───
  "Worker loop (RabbitMQ consumer)": "The email worker is a long-running process that listens to a RabbitMQ queue. When a campaign is dispatched, thousands of emails are published to the queue and the worker processes them in order.",
  "SMTP send via Mailtrap/SES": "The worker sends each individual email via SMTP — either through Mailtrap (in development/testing) or Amazon SES (in production).",
  "Dynamic SMTP TLS Handshake based on active Port (587 support)": "The SMTP connection uses STARTTLS when connecting on port 587, and implicit TLS on port 465 — automatically detected from the port number.",
  "Retry + dead-letter queue (nack on failure)": "If an email fails to send (SMTP error, timeout), the worker NAcKs the RabbitMQ message, which places it in a dead-letter queue for retry or inspection.",
  "Unsubscribe link injected into every email (HMAC-signed token)": "The worker automatically appends a cryptographically signed unsubscribe link to every email — the signature prevents forged unsubscribes.",
  "Physical business address in email footer (CAN-SPAM compliant)": "A physical mailing address is injected into every email footer — required by the US CAN-SPAM Act for bulk commercial emails.",
  "Hard bounce > auto-mark contact as bounced (SES webhook)": "When AWS SES reports a permanent delivery failure, a webhook triggers and automatically marks that contact as 'bounced' — they won't be emailed again.",
  "Spam complaint > auto-mark contact as unsubscribed (SES webhook)": "When AWS SES reports that a recipient clicked 'Mark as Spam', a webhook automatically marks them as unsubscribed.",
  "Daily send limit enforcement (per-tenant, resets at midnight, 429 on breach)": "Each tenant has a daily email send quota. Attempts to exceed it return a 429 error. The counter resets at midnight UTC.",
  "All dispatch paths enforce exclude_suppressed=True": "Every code path that builds a campaign audience (API, scheduler, bulk send) filters out suppressed contacts before dispatching — a critical correctness guarantee.",
  "Bounce classification: hard bounce suppresses, soft bounce retries 3x": "Permanent bounces (invalid address) immediately suppress the contact. Temporary bounces (mailbox full) are retried up to 3 times before suppression.",
  "Domain warmup automation (graduated daily limit increase over 30 days)": "For new sending domains, the daily limit automatically increases over 30 days following a warm-up schedule — builds sender reputation gradually.",
  "Send reputation scoring per tenant (auto-throttle on >2% bounce/>0.1% complaint)": "The system monitors each tenant's bounce and complaint rates. If thresholds are exceeded, sending is automatically throttled to protect domain reputation.",
  "FIX: Unsubscribe event logged to email_events with correct tenant_id": "Bug fix: unsubscribe events were being logged without a tenant_id, making them invisible in per-tenant analytics.",
  "FIX: Re-subscribe sets status to 'subscribed' (was 'active')": "Bug fix: the re-subscribe endpoint was setting status to 'active' instead of the correct value 'subscribed', causing filtering inconsistencies.",
  "FIX: Re-subscribe API uses NEXT_PUBLIC_API_URL (CORS resolved)": "Bug fix: the re-subscribe endpoint was being called from the browser with a server-side URL, causing CORS errors. Fixed to use the public API URL.",
  "/unsubscribe as a public route (no sidebar/header)": "The unsubscribe page is fully public and rendered without the app navigation — so recipients who aren't logged in can still unsubscribe.",
  "Unsubscribe page: auto-close tab after 3 seconds + Close Window button": "After a successful unsubscribe, the browser tab automatically closes after 3 seconds, and a 'Close Window' button is shown as a fallback.",
  "Re-subscribe option on unsubscribe page": "After unsubscribing, a button lets the contact change their mind and re-subscribe immediately.",
  "Re-subscribe page: auto-close tab after 3 seconds + Close Window button": "After re-subscribing, the tab auto-closes in 3 seconds with a 'Close Window' fallback button.",
  "[AUDIT FIX 7] Soft vs hard bounce classification — parse SES bounceType (Permanent/Transient/Undetermined) before suppressing (2d)": "Bug fix: all SES bounces currently suppress the contact regardless of type. AWS SES returns a bounceType (Permanent/Transient/Undetermined). Fix: only permanently suppress on Permanent/hard bounces; retry Transient ones.",
  "[AUDIT FIX 8] Real rolling bounce rate writer — write tenant:{id}:bounces:rolling to Redis after each bounce; circuit breaker then actually fires (1.5d)": "Bug fix: the bounce-rate circuit breaker checks a Redis key that is never actually written. Fix: write the rolling bounce count to Redis after every confirmed bounce so the circuit breaker actually receives real data.",
  "[AUDIT FIX 9] Move scheduler to standalone worker/scheduler.py — Redis SET NX EX 90 distributed lock, 60s poll, remove from FastAPI lifespan (2d)": "Architecture fix: the campaign scheduler runs inside the API process, so running two API replicas would double-schedule campaigns. Fix: extract it to a standalone worker process protected by a Redis distributed lock.",
  "[FRIEND AUDIT FIX 19] Batch DB Updates in Worker — Refactor email_sender.py to batch dispatch row updates via RPC instead of 1-by-1 HTTP calls (2d)": "Performance fix: for a 100,000-recipient campaign, the worker currently makes 100,000 individual HTTP requests to update row statuses. Fix: batch these into groups of 500 using a Postgres stored procedure, reducing HTTP calls by 99.5%.",
  "[FRIEND AUDIT FIX 20] Native DB Connection — Switch worker from Supabase PostgREST HTTP client to asyncpg TCP connection pool (1.5d)": "Performance fix: the worker talks to Postgres via Supabase's REST API (HTTP). Fix: switch to asyncpg, which connects directly to Postgres over TCP — eliminating REST overhead and enabling connection pooling.",

  # ─── PHASE 6 ───
  "Open tracking pixel endpoint (HMAC-signed) via Supabase Edge Function": "A 1×1 transparent pixel image is embedded in every email. When a recipient opens the email, their client loads the pixel, logging the open event. The URL is signed with HMAC to prevent forging.",
  "Click tracking intentionally disabled (cost optimization)": "Click tracking was evaluated but disabled — it requires redirecting every link through the tracking server, adding hosting cost and latency.",
  "SES bounce/complaint webhooks captured natively (bypass Edge Functions)": "AWS SES bounce and complaint notifications are sent directly to the FastAPI backend endpoint — no Supabase Edge Function in the middle, reducing latency.",
  "Stats aggregation (sent, opens, bounces, unsubscribes per campaign)": "For each campaign, the analytics API returns aggregated counts of sent, unique opens, total opens, bounces, and unsubscribes.",
  "Source attribution (gmail_proxy, apple_mpp, outlook, yahoo, scanner, human)": "Open events are classified by their source — Apple Mail Privacy Protection (MPP), Gmail image proxy, Outlook, or a likely human open — to filter out bot/proxy inflated metrics.",
  "FIX: Unsubscribes count cross-checks live contact status (re-subscriptions drop count)": "Bug fix: the unsubscribe count in analytics incorrectly remained high even after a contact re-subscribed. Fixed to re-check live contact status when computing the count.",
  "Contact activity log (recipient timeline in analytics API)": "An analytics endpoint that returns the full event timeline for a specific contact in a campaign — when the email was sent, opened, if they bounced, etc.",
  "Optional per-campaign click tracking (opt-in, stored in email_events)": "Click tracking can be optionally enabled per campaign — each link is wrapped in a tracking URL and clicks are stored in the email_events table.",
  "CTR stat card when click tracking enabled (unique clicks / unique opens)": "When click tracking is enabled for a campaign, a 'Click-Through Rate' stat card appears on the analytics page.",
  "Engagement over time graph (opens/bounces/unsubs by hour, first 72h)": "A time-series chart showing how opens, bounces, and unsubscribes arrived over the first 72 hours after a campaign was sent.",
  "Campaign analytics page (Sent, Opens Unique, Opens Total, Bounces, Unsubscribes)": "The main analytics screen for a campaign — shows all key engagement metrics in stat cards at the top.",
  "FIX: Recipient Activity 'Unsubscribed' column reflects live contact status": "Bug fix: the recipient activity table showed 'Unsubscribed' based on the event log rather than the current contact status, causing stale data after re-subscribes.",
  "Proxy/Scanner breakdown panel (Gmail, Apple MPP, Outlook, Yahoo, Human)": "A panel on the analytics page showing what percentage of opens came from each source type — helps tenants understand how many opens are real vs automated.",
  "FIX: Human-filtered toggle removed — all signals shown natively": "UX decision: removed the 'human only' toggle and instead show all open signals with source attribution, letting users see the full picture without filtering.",
  "Dashboard homepage sender health widget": "A widget on the main dashboard showing the current sender health score (bounce rate %, complaint rate %) and whether the domain is in good standing.",
  "Export analytics as CSV / PDF summary": "A button on the analytics page to download campaign stats as a CSV or a formatted PDF report.",

  # ─── PHASE 7 ───
  "Plans table (free/starter/pro/enterprise with limits)": "A database table defining each subscription plan and its limits — monthly email quota, max contact count, max team members, etc.",
  "Monthly email sent counter per tenant": "A counter that tracks how many emails each tenant has sent in the current billing month — reset to zero at the start of each month.",
  "Block sends when quota exceeded": "When a tenant reaches their monthly email limit, the 'send campaign' endpoint returns a 429 error and the UI shows a quota-exceeded warning.",
  "Contact count limit enforcement": "Tenants on lower-tier plans are blocked from importing contacts beyond their plan's contact limit.",
  "80% quota trigger (notification)": "When a tenant uses 80% of their monthly email quota, an in-app banner appears and a warning email is sent via the Centralized System Emailer.",
  "Worker-triggered email notifications via Centralized System Emailer": "The background worker can send system emails (campaign complete, quota warning, bounce alert) through shrmail.app@gmail.com.",
  "Plan & Usage page (progress bars for emails + contacts vs limit)": "A settings page showing two progress bars: current emails sent vs monthly limit, and current contact count vs plan limit.",
  "Upgrade plan modal (plan comparison table)": "A modal that shows a side-by-side comparison of all plans and a CTA to upgrade — triggered when users hit plan limits.",
  "In-app banner when 80% quota reached": "A yellow warning banner shown at the top of the dashboard when the tenant has used 80% of their monthly email quota.",
  "Blocked send page when quota maxed": "A page shown instead of the send button when a tenant has exhausted their monthly send quota.",
  "14-day free trial with Pro limits (no credit card required)": "New tenants get 14 days of Pro plan access without requiring a credit card — allows full feature evaluation.",
  "Overage pricing instead of hard blocking (per-email rate above quota)": "Instead of blocking sends, tenants are billed a per-email rate for emails above their plan quota — prevents surprise outages.",
  "Auto-downgrade to Free tier on subscription lapse (pause, not delete campaigns)": "If a subscription expires, the tenant is downgraded to Free automatically. Existing campaigns and contacts are preserved (paused), not deleted.",
  "Grace period on failed payment (7 days, escalating reminder emails)": "When a payment fails, the tenant keeps full access for 7 days while receiving escalating reminder emails to update their payment method.",
  "[AUDIT FIX 10] Wire quota gate to queue_campaign_dispatch() — check monthly emails_sent vs plan limit before publishing to RabbitMQ (2d)": "Bug fix: campaigns can currently be dispatched even when a tenant is over their plan quota, because the quota check is only in the API layer. Fix: add the quota gate directly inside queue_campaign_dispatch() so no path can bypass it.",

  # ─── PHASE 7.5 ───
  "Docker (Dockerfiles for API, worker, client)": "Dockerfile for each service (FastAPI backend, Python workers, Next.js frontend) so the entire stack runs in containers on any machine.",
  "docker-compose.yml": "A single file that defines and starts all services together (API, worker, frontend, RabbitMQ, Redis, Nginx) with one command.",
  "Nginx config": "The Nginx reverse proxy configuration that routes /api requests to the FastAPI backend and all other requests to the Next.js frontend.",
  "SSL/HTTPS (Let's Encrypt guide in docs)": "Documentation and a script for obtaining a free SSL certificate from Let's Encrypt and configuring Nginx to serve the app over HTTPS.",
  "CI/CD pipeline (GitHub Actions)": "A GitHub Actions workflow that automatically lints, tests, builds Docker images, and deploys to the server on every merge to the main branch.",
  "Load & Spam Testing Setup (k6 + Mail-Tester integration)": "k6 scripts for load-testing the API under heavy campaign traffic, plus Mail-Tester integration to validate spam scores before sending.",
  "Security Headers & Content Security Policy for all pages": "HTTP security headers (Content-Security-Policy, X-Frame-Options, Strict-Transport-Security) added to all responses to prevent common web attacks.",
  "API Rate Limiting (per-tenant, per-endpoint, burst protection)": "API-level rate limiting that restricts how many calls a specific tenant can make per minute per endpoint — uses Redis as the counter store.",
  "Background Job Status Table (CSV import, GDPR export, campaign send)": "A database table tracking all long-running background jobs (imports, exports, sends) so the UI can show real-time progress without polling the queue.",
  "Worker concurrency safety (locked_by column to prevent zombie tasks)": "A locked_by column on job rows prevents two worker replicas from processing the same job simultaneously.",
  "Idempotency guard (external_msg_id to prevent double-sends on retry)": "Each email send attempt is tagged with a unique external_msg_id. If the worker retries after a crash, it skips emails that were already successfully sent.",
  "GET /health on FastAPI (db + worker status)": "A health-check endpoint that returns whether the database and RabbitMQ connections are alive — used by load balancers and monitoring tools.",
  "GET /health on Worker (queue depth, last processed)": "The email worker exposes a lightweight HTTP health endpoint showing how many messages are in the queue and when the last one was processed.",
  "Centralized structured logging (ELK stack or Grafana Loki)": "All logs (API, workers, Nginx) are shipped to a central log aggregator for searching, filtering, and alerting on errors.",
  "Sentry error tracking on FastAPI + Next.js frontend": "Sentry is integrated on both the backend and frontend — uncaught exceptions are automatically reported with stack traces for fast debugging.",
  "Database backup strategy (daily, 30-day retention, monthly restore drill)": "Automated daily Supabase database backups with 30-day retention. Once a month, a restore drill verifies backups are actually recoverable.",
  "[AUDIT FIX 11] Uncomment Nginx block in docker-compose.yml; close ports 8000 and 3000 from public network (0.5d)": "Security fix: the Nginx service is commented out in docker-compose.yml, meaning the API (port 8000) and frontend (port 3000) are directly exposed to the internet. Fix: enable Nginx as the reverse proxy and remove the raw port exposures.",
  "[AUDIT FIX 12] GitHub Actions CI/CD pipeline — lint + test + Docker build + deploy on merge to main (2d)": "Automation fix: deployments are currently manual. Fix: create a GitHub Actions workflow that runs linting, test suite, builds Docker images, and deploys to the server on every merge to main.",
  "[AUDIT FIX 13] git rm frnds_contacts.csv, testmail_contacts.csv, platform/api/app.db; add *.csv and *.db to .gitignore; purge from git history (0.5d)": "Security fix: real contact CSV files and an SQLite database artifact were committed to the Git repository. Fix: remove them, add patterns to .gitignore, and purge them from the entire Git history using git filter-repo.",
  "[FRIEND AUDIT FIX 21] Dynamic Config Loading — Replace Path(__file__) .env loading with robust config.py / pydantic-settings (0.5d)": "Reliability fix: the app loads .env using a path relative to the script file, which breaks if the script is run from a different directory. Fix: use pydantic-settings which reads from environment variables properly and validates all required config at startup.",

  # ─── PHASE 7.6 ───
  "[AUDIT FIX 14] Automated test suite — 20 priority tests: auth signup/login, _suppress_contact tenant isolation, unsub token roundtrip, dispatch contact count, quota gate, bounce classification (4d)": "The tests/ directory has no actual test files — silent regressions can ship undetected. Fix: write 20 priority tests covering the most critical paths: auth endpoints, cross-tenant suppression isolation, unsubscribe token round-trips, quota enforcement, and bounce classification.",
  "[AUDIT FIX 15] Migration file renumbering — resolve duplicate 012_* and 013_* filenames for safe fresh deployment (0.5d)": "Bug fix: two migration files share the same number prefix (012_* and 013_*). On a fresh database deployment, they run in unpredictable order, creating a broken schema. Fix: renumber them to ensure every migration file has a unique sequential number.",
  "[AUDIT FIX 16] Remove dead Clerk config — delete CLERK_SECRET_KEY and CLERK_PUBLISHABLE_KEY from docker-compose.yml and .env.example (0.5d)": "Cleanup: the project previously used Clerk for auth before switching to a custom JWT model. Clerk API key references still exist in docker-compose.yml and .env.example, confusing new developers. Fix: remove all Clerk references.",
  "[FRIEND AUDIT FIX 22] Repository Pattern / DAL — Abstract direct Supabase queries out of controllers into services/db.py (4d)": "Refactoring: route handlers directly contain Supabase SQL queries like db.client.table('campaigns').select(). This makes routes hard to test and tightly coupled to the database library. Fix: extract all DB interactions into a Data Access Layer (services/db.py) that route handlers call instead.",
  "[FRIEND AUDIT FIX 23] Monolithic Worker Refactor — Split email_sender.py into modular layers (parsing, sending, injection, logging) (2d)": "Refactoring: email_sender.py handles everything in one massive try/except block — message parsing, circuit breaking, unsubscribe link injection, SMTP sending, and DB updates. Fix: split into focused modules (message_parser.py, smtp_sender.py, tracking_injector.py, dispatch_logger.py).",

  # ─── PHASE 8 ───
  "Settings landing page (/settings) with navigation cards": "A hub page at /settings with cards linking to each settings sub-section: Profile, Team, Sender Domains, API Keys, Billing.",

  # ─── PHASE 9 ───
  "Stripe integration with webhook-driven plan updates": "Stripe handles subscription billing. When Stripe confirms a payment, a webhook fires and the backend upgrades the tenant's plan in the database automatically.",

  # ─── PHASE 10 ───
  "A/B Testing: Two subject line variants sent to a split audience, winner auto-sent": "Two subject lines are sent to a small split of the audience. After a defined window, the system automatically picks the winner by open rate and sends it to the rest.",

  # ─── PHASE 11 ───
  "A public REST API (/v1/send) for transactional email sending": "A public API endpoint that lets tenants send individual, one-off emails programmatically (receipts, password resets) using their verified sender domain.",

  # ─── PHASE 12 (SCALE) ───
  "Custom domain setup wizard (enter domain > get DNS records > verify)": "A step-by-step wizard where tenants enter their sending domain, get SPF/DKIM/DMARC DNS records to add, and then the platform verifies them automatically.",
  "IP warmup status page (daily send limit and progression)": "A page showing where the tenant's sending domain is in the 30-day warm-up schedule — today's allowed send volume and the projected progression.",
  "Platform health dashboard (Redis queue depth, worker status)": "An internal admin dashboard showing real-time platform metrics: RabbitMQ queue depth, worker processing rate, Redis memory usage, and Supabase connection status.",
  "Horizontal worker scaling (stateless workers, Docker Swarm / k8s replicas)": "The email worker is refactored to be fully stateless so multiple replicas can run in parallel — enabling horizontal scaling to handle high-volume campaign blasts.",
  "Circuit breaker on SES SMTP (fail fast on consecutive failures, auto-reset)": "If the SMTP connection to SES fails 5 times in a row, the circuit breaker opens and the worker stops trying immediately — preventing pile-up of failed jobs. It auto-resets after 60 seconds.",
  "Cost monitoring dashboard (per-tenant SES cost vs plan revenue)": "An internal admin dashboard showing, per tenant, how much is being spent on AWS SES API calls vs the revenue from their current subscription plan.",
}
